version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
  web:
    build: .
    command: ["/code/wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
