# Generated by Django 2.2.11 on 2020-03-09 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('countrycode', models.CharField(max_length=3)),
                ('district', models.TextField()),
                ('population', models.IntegerField()),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('continent', models.TextField()),
                ('region', models.TextField()),
                ('surfacearea', models.FloatField()),
                ('indepyear', models.SmallIntegerField(blank=True, null=True)),
                ('population', models.IntegerField()),
                ('lifeexpectancy', models.FloatField(blank=True, null=True)),
                ('gnp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gnpold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('localname', models.TextField()),
                ('governmentform', models.TextField()),
                ('headofstate', models.TextField(blank=True, null=True)),
                ('code2', models.CharField(max_length=2)),
                ('capital', models.ForeignKey(blank=True, db_column='capital', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='world.City')),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Countrylanguage',
            fields=[
                ('countrycode', models.ForeignKey(db_column='countrycode', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='world.Country')),
                ('language', models.TextField()),
                ('isofficial', models.BooleanField()),
                ('percentage', models.FloatField()),
            ],
            options={
                'db_table': 'countrylanguage',
                'unique_together': {('countrycode', 'language')},
            },
        ),
    ]
